### ISSUE TITLE
有几点需要大佬指导?

### ISSUE THREAD

**Issue by darkfiredarkhalo** [maczyt/vue-to-react-loader#2]
你好,我们有个老的项目是基于vue,新的项目是基于react,两个项目都已经完工,但是老板想把两个项目结合到一块,即在新项目中添加一个菜单,展示老项目(vue)的所有内容.按照你的文档建了个demo,操作之后发现无法运行,有一点您写的不是很清楚,`# 增加vue文件webpack loader配置`,这部分具体怎么修改,能指点一二吗?

**Comment by darkfiredarkhalo** [comment]
clone此项目运行`react-vue`,报错,报错信息如下:
```
./src/count.vue 8:40
Module parse failed: Unterminated string constant (8:40)
File was processed with these loaders:
 * ./node_modules/vue-to-react-loader/index.js
You may need an additional loader to handle the result of these loaders.
|       const el = React.useRef(null);
|       React.useEffect(() => {
>         const app = new Function('Vue', 'var option = {
|   data() {
|     return {
```

**Comment by maczyt** [comment]
> clone此项目运行`react-vue`,报错,报错信息如下:
> 
> ```
> ./src/count.vue 8:40
> Module parse failed: Unterminated string constant (8:40)
> File was processed with these loaders:
>  * ./node_modules/vue-to-react-loader/index.js
> You may need an additional loader to handle the result of these loaders.
> |       const el = React.useRef(null);
> |       React.useEffect(() => {
> >         const app = new Function('Vue', 'var option = {
> |   data() {
> |     return {
> ```

**Comment by maczyt** [comment]
> 你好,我们有个老的项目是基于vue,新的项目是基于react,两个项目都已经完工,但是老板想把两个项目结合到一块,即在新项目中添加一个菜单,展示老项目(vue)的所有内容.按照你的文档建了个demo,操作之后发现无法运行,有一点您写的不是很清楚,`# 增加vue文件webpack loader配置`,这部分具体怎么修改,能指点一二吗?

---

首先很抱歉今天才看到，这个仓库是一个玩具，不具备融合两个框架的项目。

如果你需要把两个框架的项目集合一起，你可以搜索**微前端架构**
